version: "3.7"
services:
  mysql:
    container_name: mysql
    ports:
      - "3306:3306"
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: booking
      MYSQL_ROOT_PASSWORD: rootpassword
    command: --init-file /var/lib/init.sql
    volumes:
      - mysql:/var/lib/mysql
      - ./init.sql:/var/lib/init.sql
  backend:
    links:
      - mysql
    depends_on:
      - mysql
    container_name: backend
    ports:
      - "3000:3000"
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
volumes:
  mysql:
